server:
  port: 8012

spring:
  application:
    name: bootcupsbot

  messages:
    basename: 'messages/messages'
#    common-messages: "classpath:messages.properties"
    fallback-to-system-locale: false

  datasource:
    url: 'jdbc:postgresql://localhost:5432/bootcups?currentSchema=test'
    username: postgres
    password: 147258

  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: 'classpath:tg-bot.yaml'


logging:
  pattern.console: '%d{dd.MM.yyyy HH:mm:ss} [%t] %-5level %c{10} %M -> %msg%n'
  level:
    ru.manannikov.bootcupsbot: DEBUG