server:
  port: 8001
  servlet:
    context-path: '/api'
  compression:
    enabled: true
  address: 0.0.0.0

spring:

  datasource:
    driver-class-name: 'org.postgresql.Driver'

    url: 'jdbc:postgresql://localhost:5434/postgres'
    username: postgres
    password: 147258
    hikari:
      maximum-pool-size: 25